apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain-postgres-sc
  resources:
    requests:
      storage: 5Gi      