CREATE SCHEMA portal;
CREATE TABLE portal.films (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       varchar(40) NOT NULL,
    date_prod   date,
    kind        varchar(10),
    len         integer
);