kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
     name: postgresql-sc
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: postgresql-sc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi